version: '3'

services: 
  database:
    image: mongo
    ports: 
      - "27017:27017"
  api:
    build: .
    environment: 
      - PORT=5000
      - 

  #docker run -d --name redislocal -p 6379:6379 --restart unless-stopped -v /etc/redis/:/data redis redis-server /data

  #docker run -p 27017:27017 --name mongodblocal -d  mongo